2022-11-26 12:00:04,020 ERROR: Exception on /removebookmark/1 [GET] [in /home/theodore/.local/lib/python3.10/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/home/theodore/.local/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/theodore/.local/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/theodore/.local/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/theodore/.local/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/theodore/.local/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/theodore/Documents/GitHub/oh-no-it-s-raining/app/routes.py", line 228, in removebookmark
    db.session.delete(b)
  File "<string>", line 2, in delete
  File "/home/theodore/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2707, in delete
    self._delete_impl(state, instance, head=True)
  File "/home/theodore/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2713, in _delete_impl
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Instance '<Bookmark at 0x7f033b7b6320>' is not persisted
2022-11-26 12:01:03,568 INFO: Oh no it is raining [in /home/theodore/Documents/GitHub/oh-no-it-s-raining/app/__init__.py:51]
2022-11-26 12:01:24,528 ERROR: Exception on /removebookmark/1 [GET] [in /home/theodore/.local/lib/python3.10/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/home/theodore/.local/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/theodore/.local/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/theodore/.local/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/theodore/.local/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/theodore/.local/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/theodore/Documents/GitHub/oh-no-it-s-raining/app/routes.py", line 228, in removebookmark
    db.session.delete(b)
  File "<string>", line 2, in delete
  File "/home/theodore/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2707, in delete
    self._delete_impl(state, instance, head=True)
  File "/home/theodore/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2713, in _delete_impl
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Instance '<Bookmark at 0x7f2f7d63e9b0>' is not persisted
2022-11-26 12:01:51,603 INFO: Oh no it is raining [in /home/theodore/Documents/GitHub/oh-no-it-s-raining/app/__init__.py:51]
2022-11-26 12:01:54,821 ERROR: Exception on /removebookmark/1 [GET] [in /home/theodore/.local/lib/python3.10/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/home/theodore/.local/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/theodore/.local/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/theodore/.local/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/theodore/.local/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/theodore/.local/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/theodore/Documents/GitHub/oh-no-it-s-raining/app/routes.py", line 228, in removebookmark
    db.session.delete(b)
  File "<string>", line 2, in delete
  File "/home/theodore/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2707, in delete
    self._delete_impl(state, instance, head=True)
  File "/home/theodore/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2713, in _delete_impl
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Instance '<Bookmark at 0x7efd307dd570>' is not persisted
2022-11-26 12:05:15,542 INFO: Oh no it is raining [in /home/theodore/Documents/GitHub/oh-no-it-s-raining/app/__init__.py:51]
2022-11-26 12:05:20,301 ERROR: Exception on /removebookmark/1 [GET] [in /home/theodore/.local/lib/python3.10/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/home/theodore/.local/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/theodore/.local/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/theodore/.local/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/theodore/.local/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/theodore/.local/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/theodore/Documents/GitHub/oh-no-it-s-raining/app/routes.py", line 231, in removebookmark
    db.session.delete(b)
  File "<string>", line 2, in delete
  File "/home/theodore/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2707, in delete
    self._delete_impl(state, instance, head=True)
  File "/home/theodore/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2713, in _delete_impl
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Instance '<Bookmark at 0x7fb67d3f9570>' is not persisted
2022-11-26 12:08:20,686 INFO: Oh no it is raining [in /home/theodore/Documents/GitHub/oh-no-it-s-raining/app/__init__.py:51]
2022-11-26 12:10:00,204 INFO: Oh no it is raining [in /home/theodore/Documents/GitHub/oh-no-it-s-raining/app/__init__.py:51]
2022-11-26 12:14:32,680 INFO: Oh no it is raining [in /home/theodore/Documents/GitHub/oh-no-it-s-raining/app/__init__.py:51]
2022-11-26 12:14:36,433 ERROR: Exception on /activity/22 [GET] [in /home/theodore/.local/lib/python3.10/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/home/theodore/.local/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/theodore/.local/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/theodore/.local/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/theodore/.local/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/theodore/.local/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/theodore/Documents/GitHub/oh-no-it-s-raining/app/routes.py", line 157, in activitypage
    return render_template('activity.html', id=activityid,
  File "/home/theodore/.local/lib/python3.10/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/home/theodore/.local/lib/python3.10/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/home/theodore/.local/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/theodore/.local/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/theodore/Documents/GitHub/oh-no-it-s-raining/app/templates/activity.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/theodore/Documents/GitHub/oh-no-it-s-raining/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/theodore/.local/lib/python3.10/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/theodore/.local/lib/python3.10/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block 'doc'
    {%- block html %}
  File "/home/theodore/.local/lib/python3.10/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block 'html'
    {% block body -%}
  File "/home/theodore/.local/lib/python3.10/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block 'body'
    {% block content -%}
  File "/home/theodore/Documents/GitHub/oh-no-it-s-raining/app/templates/base.html", line 68, in block 'content'
    {% block app_content %}{% endblock %}
  File "/home/theodore/Documents/GitHub/oh-no-it-s-raining/app/templates/activity.html", line 5, in block 'app_content'
    <h1>{{ activitypage.title }}</h1>
  File "/home/theodore/.local/lib/python3.10/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'activitypage' is undefined
2022-11-26 12:15:06,784 INFO: Oh no it is raining [in /home/theodore/Documents/GitHub/oh-no-it-s-raining/app/__init__.py:51]
